import { chromium } from "playwright";
const [, , outPath] = process.argv;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 1400 } });
await page.goto("http://localhost:3411/contact", { waitUntil: "networkidle" });
await page.locator("text=Full RCM").first().click();
await page.waitForTimeout(200);
await page.locator("input").first().fill("Summit Health Partners");
await page.locator("select").first().selectOption({ index: 1 });
await page.waitForTimeout(200);
await page.locator("text=Continue").click();
await page.waitForTimeout(300);
await page.screenshot({ path: outPath, fullPage: true });
await browser.close();
