import { chromium } from "playwright";
const [, , url, selector, outPath, vw, vh] = process.argv;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: Number(vw) || 390, height: Number(vh) || 900 } });
await page.goto(url, { waitUntil: "networkidle" });
const el = page.locator(selector).first();
await el.scrollIntoViewIfNeeded();
await page.waitForTimeout(500);
await el.screenshot({ path: outPath });
await browser.close();
